folio-org/platform-complete

- package.json
Update orders and plugin-find-vendor dependencies
> FOLIO-1549 Update snapshot for stripes framework v1 part 2

- package.json
- stripes.config.js
> Re-add Calendar to snapshot.

- package.json
- stripes.config.js
> Add platform-erm as dependency.

- package.json
> bump paltform-erm version

- install-extras.json
- install.json
- okapi-install.json
- package.json
- stripes-install.json
- yarn.lock
- add mod-user-import
- update ui-users to 2.21.1
> Q1 2019 user import

- package.json
- stripes.config.js
replace ui-plugin-find-vendor with the ui-plugin-find-organization
https://issues.folio.org/browse/UIORGS-40
> Add ui plugin find organization

- package.json
- stripes.config.js
We need to deploy this plugin at testing and snapshot to continue work on ui-organizations
https://issues.folio.org/browse/UIORGS-49
> adds ui-plugin-find-contact

- install.json
- okapi-install.json
- package.json
- stripes-install.json
- yarn.lock
> Update package.json ui-checkout

- package.json
- stripes.config.js
We need to deploy this plugin at testing and snapshot to continue work on ui-organizations
https://issues.folio.org/browse/UIORGS-35
> Add ui-plugin-find-interface

- README.md
- docker/.dockerignore
- docker/Dockerfile
- docker/entrypoint.sh
- docker/nginx.conf
- yarn.lock
Adds Dockerfile to build stripes and serve in an nginx container.
> add dockerfile for serving stripes

- package.json
- stripes.config.js
setup of new Acquisitions app Invoice
https://issues.folio.org/browse/UINV-1
> UINV-1 add ui-invoice to platform

- Jenkinsfile
- package.json
- yarn.lock
> remove explicit NODE_ENV from Jenkins build env.  pin react-hot-loader

- package.json
- stripes.config.js
We need to deploy this plugin at testing and snapshot to continue work on ui-invoice
https://issues.folio.org/browse/UINV-24
> Add ui-plugin-find-po-line

- package.json
- stripes.config.js
https://issues.folio.org/browse/UIAC-1
> add ui-acquisition-units

- install-extras.json
- install.json
- okapi-install.json
- package.json
- stripes-install.json
- stripes.config.js
- yarn.lock
include repos:
* @folio/acquisition-units
* @folio/invoice
* @folio/plugin-find-po-line
* @folio/stripes-acq-components
> Include ui acq repos

- renovate.json
update renovate config to update q3.1-2019 branch
> Reconfigure renovate

- package.json
- stripes.config.js
Add recently released *find-import-profile-plugin* to *platform-complete* for the proper processing and testing.
> UIPFIMP-1: Create FindProfiles Plugin Component and add it to Platform

- package.json
- stripes.config.js
In Acquisitions we've started to work on the new module - ui-receiving
> Include ui-receiving

- install-extras.json
- install.json
- okapi-install.json
- stripes-install.json
- yarn.lock
> edge-oai-pmh v2.1.2

- package.json
- stripes.config.js
Add [ui-data-export](https://github.com/folio-org/ui-data-export) module in the scope of the [UIDEXP-8](https://issues.folio.org/browse/UIDEXP-8).
> UIDEXP-8: Add ui-data-export module

- package.json
- stripes.config.js
Add [stripes-data-transfer-components ](https://github.com/folio-org/stripes-data-transfer-components ) module in the scope of the [UIDEXP-11](https://issues.folio.org/browse/UIDEXP-11).
> UIDEXP-11: Add stripes-data-transfer-components module

- package.json
https://issues.folio.org/browse/UIQM-10
> UIQM-10 Add ui-quick-marc

- CHANGELOG.md
- package.json
- stripes.config.js
Add ui module oai-pmh. Story [MODOAIPMH-94](https://issues.folio.org/browse/MODOAIPMH-94).
> MODOAIPMH-94: add ui module oai-pmh.

- package.json
stripes 4
react-intl 4.5.3
moment 2.25.3
> STRIPES-672 stripes 4

- install-extras.json
- install.json
- package.json
- stripes-install.json
- yarn.lock
- pin backend modules by adding them to install-extras.json
- update ui-users to v3.0.5
> Ui users update q1 2020

- package.json
- stripes.config.js
https://issues.folio.org/browse/UISACQCOMP-3
> UISACQCOMP-3 remove stripes-acq-components from tenant config

- package.json
- stripes.config.js
https://issues.folio.org/browse/UICIRCLOG-1
> UICIRCLOG-1 add circulation-log module

- CHANGELOG.md
- package.json
[STRIPES-694](https://issues.folio.org/browse/STRIPES-694)
> STRIPES-694 update react-intl to v5

- Jenkinsfile
- install-extras.json
- stripes-install.json
- yarn.lock
- Lock in q2-2020 backend module releases by adding to install-extras.json
- Remove backend modules from stripes-install.json
> Lock releases q2 2020

- Jenkinsfile
- install-extras.json
- install.json
- okapi-install.json
- stripes-install.json
- yarn.lock
- Re-add edge modules back to stripes-install.json so that they are enabled for tenant.  
- Q2 updates
> mod-permissions-5.11.3, mod-login-7.0.1, mod-login-saml-2.0.1

- CHANGELOG.md
- package.json
[STRIPES-702](https://issues.folio.org/browse/STRIPES-702)
> STRIPES-702 upgrade moment to v2.29

- Jenkinsfile
- install-extras.json
- install.json
- renovate.json
- yarn.lock
- Add Okapi/version to install-extras.json.
- Modify build pipeline to perform Okapi dependency with version specified in install-extra.json.
- Update Renovate configuration (add q3-2020 branch and check for Okapi updates).
- Remove default CI .yarnrc when performing 'yarn install'
> Q3 rc bulk updates master

- package.json
- stripes.config.js
no module uses that plugin anymore, I think we can safely exclude it from platform setup
https://github.com/folio-org/platform-complete/pull/750
> remove unused plugin

- package.json
- stripes.config.js
https://issues.folio.org/browse/UIRS-3
> UIRS-3 include remote-storage to snapshot envs

- Jenkinsfile
- install-extras.json
- install.json
- okapi-install.json
- package.json
- stripes-install.json
- yarn.lock
Q3 Updates:
- mod-invoice-4.1.2
- mod-invoice-storage-4.1.2
- mod-orders-11.1.2
- mod-orders-storage-11.1.4
- ui-orders-2.2.4
Jenkins: 
- Disable platform build
> Updates and disable platform build

- CHANGELOG.md
- package.json
Increment `redux` to `v4`, `react-redux` to `v7`.
Refs [STRIPES-721](https://issues.folio.org/browse/STRIPES-721)
> STRIPES-721 upgrade to react-redux 7

- install-extras.json
Not clear that it is operating properly.
> FOLIO-3001 Remove mod-bursar-export

- install-extras.json
The folio-testing-test run failed.
> FOLIO-3025 Remove mod-ebsconet from snapshot

- install-extras.json
- install.json
- okapi-install.json
- stripes-install.json
- yarn.lock
edge-sip2-1.4.1
mod-tags-0.7.3
mod-codex-mux-2.9.3
> Q3 updates

- install-extras.json
> Add edge-dematic to install-extras in snapshot branch.

- install-extras.json
- install.json
- okapi-install.json
- yarn.lock
mod-tags-0.7.3
mod-codex-mux-2.9.3
> revert mod-tags and mod-codex-mux updates

- package.json
- stripes.config.js
Reverts folio-org/platform-complete#1058 Works w/Okapi 4.7.2 see FOLIO-3065
> Revert "remove ui-inventory-es and mod-search"

- install-extras.json
See [MODEXPS-5](https://issues.folio.org/browse/MODEXPS-5)
> FOLIO-3066 Remove mod-data-export-spring

- Jenkinsfile
- install-extras.json
- install.json
- okapi-install.json
- stripes-install.json
mod-copycat-1.0.0
edge-connexion-1.0.0
> add new R1 modules; update Jenkins pipeline

- stripes.config.js
- yarn.lock
Should fix UIIN-1474, the using new facility added in UIIN-1480.
> In stripes.config.js set maxUnpagedResourceCount to 2000

- package.json
- stripes.config.js
Add new `ui-marc-authorities` app to snapshot
[UIMARCAUTH-2](https://issues.folio.org/browse/UIMARCAUTH-2)
> UIMARCAUTH-2: Add ui-marc-authorities to snapshot

- install-extras.json
> Add edge-caiasoft to install-extras.json.

- install-extras.json
- install.json
- okapi-install.json
data-export-spring-1.0.5
data-export-worker-1.0.7
> R1 hotfix 2 - mod-data-export-worker and mod-data-export-spring

- README.md
- renovate.json
- yarn.lock
@funkymalc If you have mail filters, then the name of Renovate's branch and PR will be slightly different.
> FOLIO-3232 Renovate also assess future main branch

- install.json
- okapi-install.json
- renovate.json
- yarn.lock
> reconfigure renovate 

- package.json
- stripes.config.js
https://issues.folio.org/browse/UIPFF-1
> add ui module @folio/plugin-find-fund

- docker/Dockerfile
- yarn.lock
Change to resolve failed development dependency for BUILD UI pipeline.
> RANCHER-110 Implement changes for BUILD-UI pipeline.

- install-extras.json
- install.json
- okapi-install.json
- yarn.lock
https://issues.folio.org/browse/MODLOGSAML-130
> MODLOGSAML-130: Pac4j 5.2.1 fixing unsecure token (CVE-2021-44878) (master)

- docker/Dockerfile
- yarn.lock
***Problem description:***
Python version should be changed for docker image, that used in BUILD-UI pipeline.
Python3 became mandatory for some node components.
***Revert options:***
Can be easily reverted by python version adjustment.
> RANCHER-129 Change python version [2 to 3].

- install-extras.json
https://folio-project.slack.com/archives/CFQU1MF61/p1643644219695749
> pin mod-audit to 2.3.0-SNAPSHOT.114

- install-extras.json
- install.json
- okapi-install.json
- package.json
- stripes-install.json
- stripes.config.js
- yarn.lock
- edge-inn-reach
- mod-inn-reach
- ui-inn-reach
> Remove inn-reach modules from r1-2022 branch

- package.json
- stripes.config.js
https://issues.folio.org/browse/UIGS-1
https://github.com/folio-org/ui-gobi-settings
> UIGS-1 add new ui module

- package.json
- stripes.config.js
Apologies for the delay, PR to include service interaction frontend in snapshot's build
> Include service interaction in platform-complete

- install-extras.json
- install.json
- okapi-install.json
- yarn.lock
fix mod-circulation version from 23.0.11 to 23.1.0
> fix mod-circulation version

- package.json
- stripes.config.js
Include `@folio/plugin-find-authority`
> Add find authority plugin

- install-extras.json
- package.json
- stripes.config.js
See FOLIO-3612 UISE-155 MODCXINV-72 MODCXMUX-92 MODCXEKB-137
> FOLIO-3612 Remove deprecated codex-related modules from snapshot

- install-extras.json
- install.json
- okapi-install.json
- package.json
- stripes-install.json
- stripes.config.js
- yarn.lock
See FOLIO-3612 UISE-155 MODCXINV-72 MODCXMUX-92 MODCXEKB-137
> FOLIO-3612 Remove deprecated codex-related modules from master

- package.json
- stripes.config.js
[FOLIO-3568](https://issues.folio.org/browse/FOLIO-3568)
> FOLIO-3568: Add serials-management to snapshot

- package.json
- stripes.config.js
https://issues.folio.org/browse/UIPQB-1
> UIPQB-1 Query plugin - project setup

- README.md
- install-extras.json
- install.json
- okapi-install.json
- yarn.lock
Rename to mod-di-converter-storage and use its new release.
> FOLIO-3704 FOLIO-3683 MODDICONV-259 Rename mod-data-import-converter-storage

- install-extras.json
[MODGQL-165](https://issues.folio.org/browse/MODGQL-165)
> MODGQL-165 unpin mod-graphql on snapshot

- package.json
- stripes.config.js
https://issues.folio.org/browse/UICONSET-1
NB: Jira ticket for configuration completion of  the `ui-consortia-settings` repo was created - [FOLIO-3738](https://issues.folio.org/browse/FOLIO-3738)
> UICONSET-1 Consortia settings `ui-consortia-settings` - Project setup

- install-extras.json
temporary until required by front-end
> FOLIO-3732 Add mod-consortia to snapshot install-extras

- Jenkinsfile
- yarn.lock
> Build Stripes with Node 16. 

- Jenkinsfile
- docker/Dockerfile
- yarn.lock
> FOLIO-3777 

- package.json
- stripes.config.js
Include `stripes-marc-components`.
This PR waits for these two PRs to be merged.
https://github.com/folio-org/stripes-marc-components/pull/2 - Sonar Scan should be fixed by DevOps
https://github.com/folio-org/stripes-marc-components/pull/3 
[UISMRCCOMP-1](https://issues.folio.org/browse/UISMRCCOMP-1)
> Add stripes marc components

- package.json
- stripes.config.js
Add ui-requests-mediated to snapshot
Associated with https://github.com/folio-org/ui-requests-mediated/pull/6
https://issues.folio.org/browse/UIREQMED-14
> UIREQMED-14: Add ui-requests-mediated to snapshot

- package.json
- stripes.config.js
Include `stripes-inventory-components`.
> Add stripes-inventory-components

- install-extras.json
revert back to mod-ldp from mod-reporting.
> revert back to mod-ldp

- install-extras.json
> deploy mod-reporting module

- install.json
- okapi-install.json
- package.json
- stripes-install.json
- yarn.lock
Increase package.json NODE_OPTIONS from 4Gb to 8Gb
> FOLIO-4110 Increase NODE_OPTIONS memory allocation platform-complete snapshot

- eureka-tpl/stripes.config.js
- package.json
- stripes.config.js
https://folio-org.atlassian.net/browse/FOLIO-4111
> FOLIO-4111 Include ui-claims into platform-complete

- install.json
Removing mod-marc-migrations as per this ticket: https://folio-org.atlassian.net/browse/FOLIO-4105
> Remove mod-marc-migrations

- install-extras.json
See Slack hosted-reference-envs
> Temporarily remove mod-tlr from snapshot

- Jenkinsfile
- Jenkinsfile.build
> Remove Okapi version from install.json

- Jenkinsfile.build
> Update Jenkinsfile.build to do git pull before committing changes.

- install-extras.json
> Pin mod-requests-mediated to v1.1.0-SNAPSHOT.50

- install-extras.json
> Pin mod-tlr to v1.1.0-SNAPSHOT.64.

- install-extras.json
This reverts commit 07ccfa8e2be5dd836ba03e85c019a8ba4152bd5c.
> Revert "Pin mod-requests-mediated to v1.1.0-SNAPSHOT.50 (#3246)"

- install-extras.json
This reverts commit cdc7cc06b038ab7e3dcd2349ab49012c1819ca18.
> Revert "Re-pin mod-requests-mediated. (#3256)"

- install-extras.json
Avoid permissions problem with latest commit
> Pin mod-pubsub to v2.17.0-SNAPSHOT.258
