package.json

This requires the latest build of stripes-cli and is related to STCLI-100

Include platform-core tests in test-regression

---

package.json

Reverts folio-org/platform-complete#2.   Will wait until stripes-cli v1.4.0 is released before merging

Revert "Include platform-core tests in test-regression"

---

CHANGELOG.md
package.json
stripes.config.js

This upgrades platform-complete to use stripes-framework v1.0.0. With the exception of ui-calendar, modules have been updated to their respective versions supporting stripes framework as well. See FOLIO-1549

FOLIO-1549 Stripes framework 1.0.0

---

README.md
package.json
stripes.config.js

The ui-tenant-settings was already added in parallel.

FOLIO-2018 replace ui-organization with ui-tenant-settings on snapshot

---

package.json
stripes.config.js

Remove old ui-vendors FOLIO-1938
The replacement renamed to ui-organizations has already been here in parallel.
And see [FOLIO-2014](https://issues.folio.org/browse/FOLIO-2014)

FOLIO-1938 remove old ui-vendors from snapshot

---

package.json

stripes and the platform both have a hard dep on react but not with the
same restriction; the platform uses `^` and stripes  `~`. Probably we
only want a hard dep in one place. Until that's resolved, we need to at
least use a consistent dependency so we don't get multiple versions of
React in the build when different versions satisfy the different
dependencies (as when 16.9 was released, which is permitted by ^16.8 but
not by ~16.8).
Refs [UIIN-678](https://issues.folio.org/browse/UIIN-678)

use more conservative ~ dep on react

---

install.json
okapi-install.json
package.json
stripes-install.json
yarn.lock

Includes fixes for the following:
* [UIU-1271](https://issues.folio.org/browse/UIU-1271) (janky scrolling)
* [UIU-1263](https://issues.folio.org/browse/UIU-1263) (show up to 1000 loans)
* [UIU-1264](https://issues.folio.org/browse/UIU-1264) (do not show javascript alerts/errors when many open loans are present)

update users to v2.24.4

---

package.json

`react-router` and `react-router-dom` need to be provided by the platform as
dependencies for the platform's constituent modules to consume as
peerDependencies in order to guarantee that all modules are on the same
version. Modules may pass `<Link>` instances across module borders so we
need to be certain all modules agree on the same version of `<Link>` in
order to avoid crashing React.
Refs [STCOM-581](https://issues.folio.org/browse/STCOM-581)

STCOM-581 provide react-router as a peerDep

---

package.json

Reverts folio-org/platform-complete#287
When individual apps still include react-router v4, this causes an error:
```
ERROR:Invariant failed: You should not use <Switch> outside a <Router>
```

Revert "STCOM-581 provide react-router as a peerDep"

---

package.json

Recent updates in final-form (v4.18.6) and react-final-form (v6.3.1)
caused a lot of grief for us. From what I can tell, the handling of
`initialValues` changed dramatically. This PR locks those libraries
at v4.18.5 and v6.3.0, respectively.
Our initial patch for UIIN-875 involved provided an empty object where
none was previously required. That solved one problem but created
another: because the form now always receives an empty object on its
first render, its props _always_ change on subsequent renders when
editing existing objects and this happens to cause problems with the
barcode-validator.
There, an optimization makes an API call only if the current value is
different than the initial value. Because that initial value is now
always defined (and always empty), the API call happens …

UIIN-875 UIIN-878 lock final-form libraries

---

install.json
okapi-install.json
package.json
test/ui-testing/placeholder.js
yarn.lock

- Updated `eslint` to 6.2.1 and `eslint-config-stripes` to 5.0.0
- Enforcing `rxjs` to ^5.4.3 since none of our modules are compatible with v6
- Removed duplicate entry of `@folio/plugin-find-po-line`
- Fixed small lint warning

 Stripes 648: Security update eslint to >= 6.2.1 or eslint-util >= 1.4.1

---

package.json
test/ui-testing/placeholder.js
yarn.lock

- Updated eslint to 6.2.1 and eslint-config-stripes to 5.0.0
- Enforcing rxjs to ^5.4.3 since none of our modules are compatible with v6
- Removed duplicate entry of @folio/plugin-find-po-line
- Fixed small lint warning

Stripes 648 snapshot: Security update eslint to >= 6.2.1 or eslint-util >= 1.4.1

---

install.json
okapi-install.json
package.json
stripes-install.json
yarn.lock

ui-inventory `v1.13.1` contains changes that are not targeted at 2019-q4
and therefore should not be part of this release. `v1.13.1` was never
deployed to the test environment (bugfest) and therefore never tested
for 2019-q4, and can therefore be safely removed.

revert ui-inventory to v1.13.0

---

package.json

We could have unlocked these resolutions months ago when
@aditya-matukumalli debugged this as a problem with `initialValues` and
merged folio-org/stripes-final-form/pull/19.
Refs [STRIPES-664](https://issues.folio.org/browse/STRIPES-664)

STRIPES-664 unlock final-form resolution

---

package.json
yarn.lock

React deps should be strict with a tilde, not loose with a caret, so we
can more carefully test and be confident that things will function as
expected.

strictly depend on react 16.13

---

package.json
yarn.lock

stripes-acq-components introduced a breaking change to the vendors API with a minor release. Other minor releases of plugins were getting pulled in outside the top-level dependency tree.

Use resolutions in package.json to force removal of duplicate FOLIO libs

---

package.json

because of prototype pollution security issue. See here for more info: https://app.snyk.io/vuln/SNYK-JS-MINIMIST-559764

Ensure minimist is at least v1.2.3 in dependencies 

---

package.json

Move `react-intl` from `^4.5` to `^4.7.2` to avoid the broken `4.7.1` release,
https://github.com/formatjs/formatjs/issues/1744.

avoid buggy react-intl 4.7.1

---

package.json
stripes.config.js

Remove `stripes-data-transfer-components` dependency in advance of [`stipesDeps` approach](https://github.com/folio-org/stripes/blob/master/doc/dev-guide.md#the-package-file-stripes-entry).

Remove stripes-data-transfer-components dependency

---

CHANGELOG.md
package.json
stripes.config.js

This PR includes https://github.com/folio-org/ui-plugin-create-inventory-records to the list of dependencies so it it can show up under `folio-snapshot` and `folio-testing`

Add ui-plugin-create-inventory-records to the list of dependencies and modules

---

install-extras.json

Compared the old configuration at folio-ansible/group_vars/snapshot "add_modules"
The mod-graphql is the only one missing.

FOLIO-2781 Re-add missing extra modules

---

package.json
stripes.config.js

The mod-marccat and ui-marccat are to be deprecated. [FOLIO-2952](https://issues.folio.org/browse/FOLIO-2952) and [FOLIO-2953](https://issues.folio.org/browse/FOLIO-2953).

Remove ui-marccat FOLIO-2952

---

package.json

redux-form probably needs to be a peer-dep so that things like
stripes-components and ui-apps all have the same expectations about the
underlying redux store.
Refs [STCOR-504](https://issues.folio.org/browse/STCOR-504)

STCOR-504 force redux-form v8 on apps

---

CHANGELOG.md
package.json

Provide `react-titled` as a peer dep because the apps will pull it from
context and therefore must depend on exactly the same version.
Refs [STCOR-503](https://issues.folio.org/browse/STCOR-503)

STCOR-503 provide react-titled

---

CHANGELOG.md
package.json

Pin `@folio/stripes-cli` to `v2` via resolutions so we don't get
multiple copies of `@folio/stripes-core` and `@folio/stripes-components`
via `v1`. We can remove the resolutions entry as soon as all the tickets
linked to [STCLI-169](https://issues.folio.org/browse/STCLI-169) are closed.
Refs [STRIPES-733](https://issues.folio.org/browse/STRIPES-733)

STRIPES-733 update stripes-cli to v2

---

CHANGELOG.md
package.json

`stripes-core` wraps apps in contexts for `react-query` and `swr`, so we
need to provide those modules at the platform level so all modules can
depend on the same version as peers.
Refs [STRIPES-735](https://issues.folio.org/browse/STRIPES-735)

STRIPES-735 provide react-query, swr

---

package.json

final-form v4.20.2 contains breaking change, at least in one place. Easy fix was not found, github issue is filed for maintainers, but to unblock release we might need to lock previous version for the platform.
https://issues.folio.org/browse/UIOR-680

UIOR-680 lock final-form

---

install.json
okapi-install.json
package.json
yarn.lock

This in turn requires `stripes-webpack` ^1.2.0, which supports loading CSV files.

Upgrade stripes-cli dependency to ^2.2.0

---

install.json
package.json
stripes-install.json
yarn.lock

Yes, this is a major release when it was expected to be a patch version.
It's a long story. Some details in the discussion at
https://issues.folio.org/browse/UIIN-1451. In short, the interface provided
by mod-inventory was bumped from 10.9 to 10.10 and handling that change
in a backwards-compatible way was going to be onerous and without
any clear benefit given v6.0.0 hasn't been deployed anywhere either.

ui-inventory v7.0.0

---

package.json

part of our modules that use PersistedPaneset are broken (including bugfest env) because of release of  @rehooks/local-storage that was done yesterday
https://github.com/rehooks/local-storage/issues/77
lock version should fix the issue

lock @rehooks/local-storage

---

package.json
yarn.lock

Modules that use `PersistedPaneset` are broken due to bugs in the
release of `@rehooks/local-storage` `2.4.1`. Additional details at
https://github.com/rehooks/local-storage/issues/77
Refs [FOLIO-3128](https://issues.folio.org/browse/FOLIO-3128)

FOLIO-3128 lock @rehooks/local-storage to 2.4.0

---

package.json
yarn.lock

Some Juniper UI components are sneaking in to the Iris release as dependencies.   Pin these dependencies to Iris release versions.

pin UI dependencies to R1 2021 

---

install-extras.json
install.json
okapi-install.json
yarn.lock

Somehow mod-z3950 and mod-graphql were left out of the R2 release branch.  Re-add them both.

re-add z3950/graphql modules

---

package.json
stripes.config.js

All mod-search related endpoints and components have been implemented
directly in ui-inventory since UIIN-1567. Consequently, ui-inventory-es
may be removed.
Refs [UISEES-70](https://issues.folio.org/browse/UISEES-70), [UIIN-1567](https://issues.folio.org/browse/UIIN-1567)

UISEES-70 remove ui-inventory-es given ui-inventory has facets

---

CHANGELOG.md
package.json

Provide `rxjs` `v6` as a dependency, allowing apps to include it as a
peer-dependency.
Refs [STRIPES-723](https://issues.folio.org/browse/STRIPES-723)

STRIPES-723 provide rxjs v6

---

CHANGELOG.md
package.json

[`react-intl` `v5.21.1` includes breaking changes](https://github.com/formatjs/formatjs/issues/3263) to how null values are
handled in `<FormattedMessage>` values (previously they were replaced
with empty strings, now they are replaced by their keys).
Refs [FOLIO-3342](https://issues.folio.org/browse/FOLIO-3342)

FOLIO-3342 lock to react-intl v5.21.0

---

package.json

Remove eslint-config-stripes from devDependencies. it was only there to lint the nightmareJS tests which are no longer there.

Remove eslint-config-stripes from devDeps

---

install-extras.json
install.json
okapi-install.json
yarn.lock

There were no changes to the code, only dependency updates:
https://github.com/folio-org/mod-permissions/compare/v5.13.2...v5.14.4

Bump mod-permissions from 5.13.2 to 5.14.4

---

CHANGELOG.md
package.json

The owner of `colors` [sabotaged the package in releases > 1.4.0, adding
an infinite loop and verbose log output](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/).
Refs [FOLIO-3383](https://issues.folio.org/browse/FOLIO-3383).

FOLIO-3383 avoid sabotaged colors > 1.4.0

---

docker/Dockerfile

***Problem description:***
Python version should be changed for docker image, that used in BUILD-UI pipeline.
Python3 became mandatory for some node components.
***Revert options:***
Can be easily reverted by python version adjustment.

RANCHER-129 Adjust python version for BUILD-UI pipeline

---

install-extras.json
install.json
okapi-install.json
yarn.lock

The core platform team decided that mod-login-saml v2.4.0 should be used for hotfixing Iris, Juniper and Kiwi.
mod-login-saml v2.4.0 was released with pac4j bumped from 5.1.4 to v5.2.1 fixing the unsecure token security issue:
* https://nvd.nist.gov/vuln/detail/CVE-2021-44878
* https://issues.folio.org/browse/MODLOGSAML-130
mod-login-saml v2.4.0 contains other minor bug fixes and library updates, but no new features.
The previous mod-login-saml release is v2.3.2 and uses pac4j v4.3.0 and vertx-pac4j v5.0.2-FOLIO.1 and is affected by the unsecure token issue, however, pac4j v4.* and vertx-pac4j 5.* are no longer maintained and don't get security fixes.
(cherry picked from commit 5e3a016d98e1261ba6a2820aa0eecc6a63f35364)

MODLOGSAML-130: mod-login-saml v2.4.0, Pac4j 5.2.1 (R1-2021)

---

install-extras.json
install.json
okapi-install.json
yarn.lock

The core platform team decided that mod-login-saml v2.4.0 should be used for hotfixing Iris, Juniper and Kiwi.
mod-login-saml v2.4.0 was released with pac4j bumped from 5.1.4 to v5.2.1 fixing the unsecure token security issue:
* https://nvd.nist.gov/vuln/detail/CVE-2021-44878
* https://issues.folio.org/browse/MODLOGSAML-130
mod-login-saml v2.4.0 contains other minor bug fixes and library updates, but no new features.
The previous mod-login-saml release is v2.3.2 and uses pac4j v4.3.0 and vertx-pac4j v5.0.2-FOLIO.1 and is affected by the unsecure token issue, however, pac4j v4.* and vertx-pac4j 5.* are no longer maintained and don't get security fixes.
(cherry picked from commit 5e3a016d98e1261ba6a2820aa0eecc6a63f35364)

MODLOGSAML-130: mod-login-saml v2.4.0, Pac4j 5.2.1 (R2-2021)

---

install-extras.json
install.json
okapi-install.json
yarn.lock

The core platform team decided that mod-login-saml v2.4.0 should be used for hotfixing Iris, Juniper and Kiwi.
mod-login-saml v2.4.0 was released with pac4j bumped from 5.1.4 to v5.2.1 fixing the unsecure token security issue:
* https://nvd.nist.gov/vuln/detail/CVE-2021-44878
* https://issues.folio.org/browse/MODLOGSAML-130
mod-login-saml v2.4.0 contains other minor bug fixes and library updates, but no new features.
The previous mod-login-saml release is v2.3.2 and uses pac4j v4.3.0 and vertx-pac4j v5.0.2-FOLIO.1 and is affected by the unsecure token issue, however, pac4j v4.* and vertx-pac4j 5.* are no longer maintained and don't get security fixes.
(cherry picked from commit 5e3a016d98e1261ba6a2820aa0eecc6a63f35364)

MODLOGSAML-130: mod-login-saml v2.4.0, Pac4j 5.2.1 (R3-2021)

---

install-extras.json
install.json
stripes-install.json
yarn.lock

edge-sip2 have had been disabled because of incompatible circulation interface: #1848
edge-sip2 has been changed to accept the interface circulation 13.0
and edge-sip2-2.2.0 has been released with this interface and implementation change.
Now it can be enabled again.

SIP2-109: Add edge-sip2-2.2.0

---

install.json
package.json
stripes-install.json
yarn.lock

Bump `@folio/users` to `8.0.0`, requiring `permissions` interface `5.5`
in order to update the `ui-users.editperms` permission set with
`perms.users.assign.mutable` and `perms.users.assign.immutable` so they
can continue to grant permissions they do not already own.
Refs [UIU-2549](https://issues.folio.org/browse/UIU-2549)

UIU-2549 bump @folio/users to 8.0

---

.github/workflows/spring-cve-2022-22965.yml
yarn.lock

List spring-beans existence and show vulnerable and fixed versions.

FOLIO-3466: Spring4Shell: spring-beans RCE Vuln (CVE-2022-22965)

---

Jenkinsfile.build

Add echo/wait to Jenkinsfile.build cleanup phase to flush buffer from Ansible playbook plugin and ensure console log is sensible.

FOLIO-3445 Jenkins cleanup wait

---

README.md
doc/finding-module-versions.md
yarn.lock

This came up in a support request on Slack, and I thought it would be useful to have a document to point to.

Add document on finding module versions in a flower release

---

CHANGELOG.md
package.json

We locked to `"5.21.0"` in #1625 to resolve [FOLIO-3342](https://issues.folio.org/browse/FOLIO-3342), a breaking
change in a patch release of react-intl. That change was subsequently
reverted, so our lock can be reverted as well. This will also allow the
platform to be more tolerant of dependency glitches in other repos (e.g.
FOLIO-3477).
Refs [FOLIO-3503](https://issues.folio.org/browse/FOLIO-3503), [FOLIO-3477](https://issues.folio.org/browse/FOLIO-3477), [FOLIO-3342](https://issues.folio.org/browse/FOLIO-3342)

FOLIO-3503 unlock react-intl from v5.21.0

---

package.json
yarn.lock

Apps with loose (`*`) optional-deps on plugins allow incompatible
versions of those plugins to leak into the build. Even though the
platform's package.json may depend on `"ui-plugin-find-foo": "3.2.0"`,
if there is an app with a looser dependency that permits a later
version, then the later version will be pulled into the build.
If the later version is incompatible, e.g. because it has a peer
dependency on a stripes-acq-components version that is not present in the
build, this can lead to corruption in the UI (e.g. missing
translations).
The following plugins are included by one or more apps with `*` deps and
therefore have `resolutions` entries here copied directly from their
strict `dependencies` version in order to guarantee that only compatible
versions are included:
* …

FOLIO-3547 pin plugin deps to guarantee compatibility

---

install-extras.json
install.json
okapi-install.json
yarn.lock

https://issues.folio.org/browse/MODINVSTOR-944
"GET Instance Set by CQL - MG back-port"
This performance feature has been back-ported to Morning Glory and released as mod-inventory-storage 24.1.0 for Morning Glory as discussed on #prokopovych Slack channel.

Upgrade mod-inventory-storage from 24.0.4 to 24.1.0 for MG

---

package.json
yarn.lock

- Fulfills [STRIPES-726](https://issues.folio.org/browse/STRIPES-726).
- Prevents all packages from running scripts when installing.
- The one script needed is `stripes-core` building icons which is allowed by adding `npm rebuild sharp` as a `postinstall` step which automatically runs after `install`.

Ignore scripts and add postinstall step to build icons

---

CHANGELOG.md
package.json

Provide third-party dependencies that stripes and UI applications share so we have a guarantee of compatibility. An identical version is a requirement, enforced by React, in context Provider/Consumer relationships, and while it's possible/probable that you'll get compatible versions when both parties include deps like `^1.2.3`, it's not technically a guarantee.
This also resolves several build warnings for apps that (rightly) expect some of these things to be provided by the platform but in fact they were only being provided directly by other apps and were being hoisted.
The following libraries are being added:
* final-form
* react-final-form
* final-form-arrays
* react-final-form-arrays
* redux-observable
* zustand
Refs [FOLIO-3602](https://issues.folio.org/browse/FOLIO-3602)

FOLIO-3602 provide additional shared third-party dependencies

---

CHANGELOG.md
package.json

`@folio/stripes-erm-components` bumped from `v6` to `v7` for 2022-R3 and updated apps' peer-deps accordingly, but forgot to update the version here, which is the only version that actually matters since `yarn` doesn't satisfy peers from deps when building at the platform level (sigh), rather, it only satisfies direct-deps of the platform.
This resolves build warnings like the following when running `yarn install`:
```
warning " > @folio/agreements@8.4.100000461" has incorrect peer dependency "@folio/stripes-erm-components@^7.0.1".
```
Refs [FOLIO-3620](https://issues.folio.org/browse/FOLIO-3620)

FOLIO-3620 bump stripes-erm-components major version

---

CHANGELOG.md
package.json

Avoid the buggy 5.11.0 release that appears to be incompatible with webpack-virtual-modules. Additional details at
folio-org/stripes-webpack#81. Locally, locking `enhanced-resolve` in `stripes-webpack` was sufficient to get us to a successful build; alas, CI builds continue to fail because 5.11.0 continues to sneak in 🤨 . 
Refs [STRWEB-61](https://issues.folio.org/browse/STRWEB-61)

STRWEB-61 lock enhanced-resolve to 5.10.0

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/STRWEB-62
This PR removes `enhanced-resolve` resolutions entry since this was fixed directly in webpack: https://github.com/webpack/enhanced-resolve/pull/364

STRWEB-62: Remove enhanced-resolve resolutions entry

---

CHANGELOG.md
package.json

stripes-erm-components has moved on to version 8, bump platform complete dependency to reflect that
Refs [ERM-2235](https://issues.folio.org/browse/ERM-2235) and [ERM-2453](https://issues.folio.org/browse/ERM-2453)

Bump version of stripes-erm-components

---

install-extras.json

[MODDICONV-259](https://issues.folio.org/browse/MODDICONV-259)
[FOLIO-3683](https://issues.folio.org/browse/FOLIO-3683)
The new [ModuleDescriptor](https://github.com/folio-org/mod-di-converter-storage/blob/master/descriptors/ModuleDescriptor-template.json) utilises the "replace" facility, and retains the same interface name and version.

FOLIO-3683 MODDICONV-259 Rename mod-data-import-converter-storage mod-di-converter-storage

---

CHANGELOG.md
package.json

The 2023-R1/Orchid release of stripes and its constituent libraries will contain breaking changes, including the removal of many props that have long been deprecated.

bump @folio/stripes to v8.0.0

---

CHANGELOG.md
package.json

Implementing swr was a [POC](https://issues.folio.org/browse/STCOR-516); we chose react-query instead. 
Refs [STCOR-611](https://issues.folio.org/browse/STCOR-611)

STCOR-611 remove swr cruft

---

install-extras.json

The hourly builds are too broken. Pin to previous working 1.10.2000317, while a fix is prepared.
[MODGQL-165](https://issues.folio.org/browse/MODGQL-165)

MODGQL-165 Pin mod-graphql to previous

---

package.json

Set the minimum version of `redux` to the version currently in use (`4.2.1`) as part of coordinating the version across all repositories.
Note that there is *zero* impact from this change; all it does it align the minimum version being requested with the current version already in-use.
Refs [STRIPES-860](https://issues.folio.org/browse/STRIPES-860)

STRIPES-860 align redux semver with in-use version

---

CHANGELOG.md
package.json

* Bump `react` to `v18`, and correspondingly `@folio/stripes` to `v9` and `@folio/stripes-cli` to `v3`.
Refs [STRIPES-870](https://issues.folio.org/browse/STRIPES-870)

STRIPES-870 bump react to v18

---

install-extras.json
install.json
okapi-install.json
package.json
yarn.lock

stripes-cli ~2.6.3 requires stripes-webpack ~4.1.x. stripes-cli ~2.7.x
requires stripes-webpack ~4.2.x. :shame: We accidentally introduced
breaking changes in stripes-webpack in v4.2.0 without realizing it;
additional details at https://github.com/folio-org/stripes-cli/pull/307.
This PR aligns deps related to stripes-cli ~2.6.3.

align stripes-webpack, stripes-cli on Nolana versions

---

CHANGELOG.md
package.json

Bump `stripes-erm-components` to `^8.0.0` for stripes v9 and react v18 compat.
Refs [ERM-2989](https://issues.folio.org/browse/ERM-2989)

ERM-2989 bump stripes-erm-components to v8

---

package.json
yarn.lock

- Step was running both `yarn install` followed immediately by `yarn install --ignore-scripts`, but since the first run omits the flag, the second run is pointless and wasteful.
- CI builds and local devs can use `--ignore-scripts` as needed (CI build scripts already do this).
- Reverts [STRIPES-726](https://issues.folio.org/browse/STRIPES-726)

Remove install step that is ignored and doesn't serve any purpose.

---

CHANGELOG.md
package.json

Bump `react-titled` to v2 in order to align with the version already provided by `@folio/stripes`. v2 provides react v18 compatibility, among other modernizations. This is less "make an upgrade" than "make the platform's version consistent with the upgrade that has already taken place in applications."

Bump react-titled to v2

---

package.json
yarn.lock

renovate is a super helpful tool, but it must not make changes to the versions we specify in `resolutions`. Recent changes (#2469, #2459) updated fixed versions and reintroduced old bugs (STCOM-1148, and a node incompatibility since `@rehooks/local-storage` `2.4.5` wants `v18` but something else relies on `v16`).
This PR restores the original versions of both `react-virtualized-auto-sizer` (aka RVAS) and `@rehooks/local-storage` and removes the semver flexibility (`~` or `^`) of other third-party dependencies in `resolutions` in case we figure out how to configure renovate to always leave fixed versions as-is. 
Refs [FOLIO-3768](https://issues.folio.org/browse/FOLIO-3768)

FOLIO-3768 restore intentional R1-2023 versions

---

CHANGELOG.md
stripes.config.js

Do not clear the console log on logout. This is less secure, but in a test environment it may help with debugging.
Refs [STCOR-761](https://issues.folio.org/browse/STCOR-761)

STCOR-761 preserve console log on logout

---

CHANGELOG.md
stripes.config.js

Set `useSecureTokens: true` in `stripes.config.js` to turn on RTR.
See also folio-org/stripes-core/pull/1376
Refs [STCOR-671](https://issues.folio.org/browse/STCOR-671), [FOLIO-3627](https://issues.folio.org/browse/FOLIO-3627)

STCOR-671 use secure tokens (RTR)

---

install-extras.json

- Fulfills [FOLIO-3993](https://folio-org.atlassian.net/browse/FOLIO-3993)
- `mod-login-saml` has been marked as optional by https://github.com/folio-org/ui-tenant-settings/pull/391, but we would still like it to be included in community snapshot builds. Since it was automatically dropped when marked optional, re-adding it through `install-extras.json`.

FOLIO-3993 Add optional login-saml interface

---

package.json
yarn.lock

`favicons` and `sharp` were added to resolutions in #2644, probably to avoid pulling `favicons` `7.1.5` in a build that was running without a `yarn.lock` file before `@folio/stripes-webpack` `5.1.0` was published (which similarly locks it to `v7.1.4`), but then dependabot updated in PR #2645. Whoops. Bad dependabot. No biscuit! We depended on that specific version because we wanted that specific version.
Refs [FOLIO-3997](https://folio-org.atlassian.net/browse/FOLIO-3997), [STRWEB-105](https://folio-org.atlassian.net/browse/STRWEB-105)

FOLIO-3997 omit unnecessary favicons, sharp dependencies #2724

---

package.json
yarn.lock

`favicons` and `sharp` were added to resolutions in #2644, probably to avoid pulling `favicons` `7.1.5` in a build that was running without a `yarn.lock` file before `@folio/stripes-webpack` `5.1.0` was published (which similarly locks it to `v7.1.4`), but then dependabot updated in PR #2645. Whoops. Bad dependabot. No biscuit! We depended on that specific version because we wanted that specific version.
Refs [FOLIO-3997](https://folio-org.atlassian.net/browse/FOLIO-3997), [STRWEB-105](https://folio-org.atlassian.net/browse/STRWEB-105)

FOLIO-3997 omit unnecessary favicons, sharp dependencies

---

package.json

Bump zustand from `^4.1.1` to `^4.5.4` to avoid the buggy `v4.5.3` release (https://github.com/pmndrs/zustand/discussions/2621).
Builds with v4.5.3 fail:
```
ERROR in ./node_modules/zustand/esm/index.js 1:0
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import { createStore } from 'zustand/vanilla';
| export * from 'zustand/vanilla';
| import ReactExports from 'react';
```
Refs [FOLIO-4030](https://folio-org.atlassian.net/browse/FOLIO-4030)

FOLIO-4030 bump zustand to ^4.5.4 to avoid buggy 4.5.3 release

---

install-extras.json

This is to prevent the Keycloak-integrated modules that offer the same interfaces from causing an error in building platform-complete or in building a reference environment. FOLIO-4029.

FOLIO-4029 Update install-extras.json to request mod-login and mod-authtoken

---

install-extras.json

Cater for multiple interfaces upcoming mod-reporting. Needed while testing new Workflows ModuleDescriptor.

FOLIO-3994 Add mod-ldp to snapshot install-extras.json

---

package.json

Typescript doesn't believe in semver and published breaking changes between v5.5.4 and v5.6.2. Pinning to v5.6.4, the last-known-compatible version, here in the platform will allow our builds to get back on track while we investigate if/how/when to pursue compatibility with v5.6.
Refs [FOLIO-4061](https://folio-org.atlassian.net/browse/FOLIO-4061)

FOLIO-4061 pin typescript to 5.5, avoiding breaking changes in 5.6

---

eureka-tpl/package.json

Subsequent to STCOR-875 and UIU-3183, Eureka UI work will be part of the mainline in all UI repositories and thus does not require special handling in `package.json` any longer.
Refs [STCOR-875](https://folio-org.atlassian.net/browse/STCOR-875), [UIU-3183](https://folio-org.atlassian.net/browse/UIU-3183)

STCOR-875 UIU-3183 use default branches of stripes-core, ui-users

---

package.json

Many packages published by DefinitelyTyped use loose dependencies like
```
"@types/react": "*",
```
allowing non-compliant types from react v19 to leak into our v18-based build.

resolve @types/react to v18 to avoid v19 leaking in

---

install-extras.json
install.json
okapi-install.json
yarn.lock

https://folio-org.atlassian.net/browse/FOLIO-4160
Move mod-authtoken to the top so that it gets installed early.
Then it is available when enabling a second module that requires a token to access a permission protected API of a third module.
Modules using authtokens don't have the authtoken okapi interface in their requires section of in their module descriptor because they don't use the mod-authtoken HTTP API but the token feature of Okapi. Therefore we need to use the install order to ensure mod-authtoken availability.
https://folio-project.slack.com/archives/CFQU1MF61/p1725977004958399?thread_ts=1725933118.184429&cid=CFQU1MF61
mod-authtoken requires mod-permissions and mod-users therefore we use this natural order:
1. mod-permissions
2. mod-users
3. mod-authtoken

FOLIO-4160: Enable mod-authtoken early (R1-2024)

---

install-extras.json

https://folio-org.atlassian.net/browse/FOLIO-4160
Move mod-authtoken to the top so that it gets installed early.
Then it is available when enabling a second module that requires a token to access a permission protected API of a third module.
Modules using authtokens don't have the authtoken okapi interface in their requires section of in their module descriptor because they don't use the mod-authtoken HTTP API but the token feature of Okapi. Therefore we need to use the install order to ensure mod-authtoken availability.
https://folio-project.slack.com/archives/CFQU1MF61/p1725977004958399?thread_ts=1725933118.184429&cid=CFQU1MF61
mod-authtoken requires mod-permissions and mod-users therefore we use this natural order:
1. mod-permissions
2. mod-users
3. mod-authtoken

FOLIO-4160: Enable mod-authtoken early (master)

---

install-extras.json

https://folio-org.atlassian.net/browse/FOLIO-4160
Move mod-authtoken to the top of install-extras.json so that it gets installed early.
Then it is available when enabling a second module that requires a token to access a permission protected API of a third module.
Modules using authtokens don't have the authtoken okapi interface in their requires section of in their module descriptor because they don't use the mod-authtoken HTTP API but the token feature of Okapi. Therefore we need to use the install order to ensure mod-authtoken availability.
https://folio-project.slack.com/archives/CFQU1MF61/p1725977004958399?thread_ts=1725933118.184429&cid=CFQU1MF61
mod-authtoken requires mod-permissions and mod-users therefore we use this natural order:
1. mod-permissions
2. mod-users
3. mod-authtoken

FOLIO-4160: Enable mod-authtoken early (R2-2024-Edge)

---

install-extras.json

https://folio-org.atlassian.net/browse/FOLIO-4160
Move mod-authtoken to the top of install-extras.json so that it gets installed early.
Then it is available when enabling a second module that requires a token to access a permission protected API of a third module.
Modules using authtokens don't have the authtoken okapi interface in their requires section of in their module descriptor because they don't use the mod-authtoken HTTP API but the token feature of Okapi. Therefore we need to use the install order to ensure mod-authtoken availability.
https://folio-project.slack.com/archives/CFQU1MF61/p1725977004958399?thread_ts=1725933118.184429&cid=CFQU1MF61
mod-authtoken requires mod-permissions and mod-users therefore we use this natural order:
1. mod-permissions
2. mod-users
3. mod-authtoken

FOLIO-4160: Enable mod-authtoken early (R2-2024-Edge-Consortia)

---

install-extras.json

Avoid pulling in mod-okapi-facade.

Pin mod-licenses and mod-service-interaction to specific builds.

---

install-extras.json

Because mod-okapi-facade now offers the `okapi` interface, the "okapi" module must be specified for Okapi-based builds to prevent mod-okapi-facade from being pulled in by dependency resolution.
Also remove pinning of mod-licenses and mod-service-interaction to versions that don't require the `okapi` interface.
FOLIO-4169

Specify "okapi" module in install-extras.json

---

CHANGELOG.md
package.json

* update `react-intl` to v7
* update `@folio/stripes` to v10
* move `@folio/stripes-cli` into dependencies, where it has always belonged
* removed unused dev-deps (probably they can all be removed but this requires more investigation and testing)
Refs [STRIPES-960](https://folio-org.atlassian.net/browse/STRIPES-960), [STRIPES-961](https://folio-org.atlassian.net/browse/STRIPES-961)

STRIPES-960 STRIPES-961 update react-intl, stripes

---

CHANGELOG.md
package.json

* Provide `@folio/stripes-build` as a direct-dep instead of `@folio/stripes-cli` (now moved to a dev-dep), in order to provide a streamlined build in a production environment. `@folio/stripes-build` is a stripped-down version of `@folio/stripes-cli` with drastically fewer dependencies and thus a smaller surface area for security vulnerabilities. On release branches, `@folio/stripes-cli` can/should be removed entirely. 
* Clean up test script cruft.
Refs [FOLIO-4255](https://folio-org.atlassian.net/browse/FOLIO-4255)

FOLIO-4255 build with stripes-build instead of stripes-cli

---

CHANGELOG.md
package.json

Bump `react-intl` to `^7.1.9` to avoid https://github.com/formatjs/formatjs/issues/4915.
Refs [FOLIO-4262](https://folio-org.atlassian.net/browse/FOLIO-4262)

FOLIO-4262 bump react-intl to ^7.1.9

---

CHANGELOG.md
package.json

It turns out #3272 had the right idea but was a bit too soon as react-intl v7.1.9 was still broken,
https://github.com/formatjs/formatjs/issues/4918.
Refs [FOLIO-4263](https://folio-org.atlassian.net/browse/FOLIO-4263)

FOLIO-4263 bump react-intl to ^7.1.10

---

package.json

`@folio/stripes-cli` was inadvertently removed in #3272. Bad developer! No biscuit!

restore @folio/stripes-cli

---

install.json
package.json
stripes-install.json
yarn.lock

ui-calendar v12.0.0 (Sunflower) released https://github.com/folio-org/ui-calendar/releases/tag/v12.0.0
https://open-libr-foundation.slack.com/archives/CGPMHLX9B/p1743597459352799

Update @folio/calendar to 12.0.0

---

package.json

This was missed in the Sunflower changes, stripes-erm-components was moved to v10.0.x.
This is a bit of a grey area to me as to who is responsible for keeping this up to date. The last bump was performed by @zburke and the one before that was me.
I see that `stripes-authority-components`, `stripes-inventory-components`, and `stripes-marc-components` are set up to use `>=` for snapshot, and so I'd like to mirror that here and avoid the dance needing to happen every time a major bump occurs.
Of course the expectation is that major releases will be announced in the `#folio-releases` channel and end up in the bugfest/release environments as before

build: change stripes-erm-components dep for snapshot to >=

---

install-extras.json
package.json

ui-agreements was [previously pinned](https://github.com/folio-org/platform-complete/pull/3429) as [a dependency was accidentally declared as a devDependency](https://github.com/folio-org/ui-agreements/pull/1427), causing the build to fail.
This has since [been rectified](https://github.com/folio-org/ui-agreements/pull/1429)

Revert to pulling in latest ui-agreements now dependency has been fixed
